app:
  FirstSub: '嗨！这里是百晓生，一个智能助理的雏形。
  
请保持关注，在这里可以获取免费使用的全模型api。

便宜又好用的ai站：<a href="https://www.a0.chat/" target="_blank" style="color: red;">www.a0.chat</a>

如要领取每日免费 50万 Tokens 的全模型api，请回复文字：领取'
  UsedSub: "今日你已经领取过了～"
  OtherSub: "不要乱发消息哦～"
  TokenSub: '恭喜你打开 AI 世界的大门🎉

🎁成功获取到一枚 KEY: %s

🔑KEY 包含 50万Tokens 体验额度，有效期 1 天，每 24 小时可领一枚。

🚗配合接口地址使用：https://api.bxsapi.com/

😆不够清楚？👉<a href="https://xx7tl7g4rg.feishu.cn/docx/ImR1d2MI1oZvh1xz5DxcekWsnid/" target="_blank" style="color: red;">查看使用教程</a>

👉<a href="https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=HJiFQMzB3DxCBas1uDTijpn0bs2Firn1&authKey=OB%2FCNRfKzzanEeue7EXGKosOsGrLosae4AeGP1mHqDhYwz4voBaIhCnCBiXfUklb&noverify=0&group_code=814702872/" target="_blank" style="color: red;">加群了解更多</a>

😎提示：该密钥同样支持在其他支持 OpenAI 服务的场景中使用，如沉浸式翻译，学术GPT等等，到期或用完将无法使用，作为免费服务本站不提供任何技术支持，敬请理解。'

sever:
  # 服务端口 如果使用 docker 部署请使用服务器本机 ip 地址
  RdsHost: "localhost"
  RdsPort: 6379
  RdsUser: ""
  RdsDB: 0
  RdsPass: ""
  Authorization: ""
  APIUrl: ""
  WxToken: ""
  #根据自己的需求修改 50000 是 1 刀
  Limit: 500000
  #过期时间 默认 1 天，最小是1天！不要写 0
  Expire: 1
